### ISSUE TITLE
Support retrying of network commands

### ISSUE THREAD

**Issue by richardjrossiii** [parse-community/Parse-SDK-dotNET#110]
Currently, the SDK does not perform any retry logic when a network request fails, unlike all of our other platforms.

We need to have a way to easily retry a network request in a cross-platform way.

**Comment by TobiasPott** [comment]
I'm unsure about the current state of this issue and whether or not any retry logic was added in the past since this issue was created.
I've picked up this issue and will create a new issue for evaluation of this in the near future.
If you encounter the problem with the latest version of the SDK available in the master branch, feel free to reopen this issue or create a new one to discuss possible solutions or provide a pull request for a fix.
