### ISSUE TITLE
Support ASP.NET

### ISSUE THREAD

**Issue by richardjrossiii** [parse-community/Parse-SDK-dotNET#121]
Currently, our SDK does not support ASP.NET as a platform. It would appear that there are a few people who are attempting to currently use our SDK in ASP.NET platforms (see #117), so we should probably eventually support this.

This issue will track our roadmap and remaining issues for ASP.NET support, as I continue investigating into that front.

If you would like to help, please leave a comment on this issue, and I can help you find an appropriate sized piece of work related to this issue.

**Comment by PunkStarStudios** [comment]
Argh... NOW I've just read this... ARGH.

Is this still the case?
Any chance someone out there has sample code for a website using the parse .net SDK?

**Comment by ciozmi** [comment]
Hi, has any progress been done regarding this issue? If not, what would be a suitable approach or starting point to have some sort of support with ASP.NET? The biggest issue is the one mentioned in issue #269 referenced above, where pretty much any static classes and variables relating to ParseUser do not work as expected in server-client environment

**Comment by TobiasPott** [comment]
I picked this issue up for further evaluation of ASP.NET support using the latest version.
I'll close this issue for now and invite anyone to reopen it if any further information was gained regarding ASP.NET.

**Comment by TheFanatr** [comment]
ASP.NET Core is now fully supported; see the readme section on [server-side use](https://github.com/parse-community/Parse-SDK-dotNET#server-side-use). Essentially, `ParseClient` is now instantiable and hosts the entire internal service pipeline used by SDK operations. This pipeline can be configured via the `ParseClient` constructors using the `IServiceHubMutator` interface; the SDK includes one which makes it so that the `ICurrentUserController` hosted in the service hub does not use a real file-backed cache and when clones of `ParseClient.Instance` are made, it does not carry over any information about the currently authenticated user, so `ParseClient` can be dependency-injected with ease and the SDK can be used to manage multiple concurrently-authenticated users.

**Comment by TobiasPott** [comment]
@TheFanatr Thank you for your fast response and clarification. I'll take this up anyway to evaluate creating an sample to use it with ASP.NET to get users started in the future.

**Comment by TheFanatr** [comment]
@TobiasPott You can try to use my Server-Side Blazor sample or just use it as a reference to make another one. If it doesn’t work, let me know and I’ll fix it.
