### ISSUE TITLE
Improve clarity of installed version inside a Unity project

### ISSUE THREAD

**Issue by jeanfabre** [parse-community/Parse-SDK-dotNET#159]
Following a tricky issue https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/155

I strongly suggest to prevent further misunderstanding that the Unity Package for Parse includes in readme the actual version of the dll. It will prevent us wondering what version of Parse we have, and unecessary frustrations from all parties.

Thanks,

 Jean

**Comment by richardjrossiii** [comment]
(Assuming the unity asset packager ever works again), yes, I agree, this sounds like a good idea, and shouldn't be too hard to implement.

**Comment by TobiasPott** [comment]
This problem is solved with the latest version in the master branch and the unified code base which no longer requires separate assemblies for Unity or other platforms.
Please refer to the Readme [use-in-unity-client](https://github.com/parse-community/Parse-SDK-dotNET#use-in-unity-client) section for details about the use.
