### ISSUE TITLE
Parse Unity SDK only works with Android and IOS

### ISSUE THREAD

**Issue by VanWardawg** [parse-community/Parse-SDK-dotNET#160]
I'm trying to build a cross platform app with Unity and I love Parse but I want to take advantage of windows 10 and WebGL platforms. Is there a timeline for when those platforms will become supported or some documentation on how to use those platforms if they are supported?

Thanks,
Kevin Hinton

**Comment by Gustavo23** [comment]
The same, here.

**Comment by richardjrossiii** [comment]
Yes, this is an issue we're aware of and are hoping to have fixed soon. Essentially windows 10 cannot be supported due to the fact that it uses native .NET there, which has their own implementation of System.Threading.Tasks that is incompatible with our custom one for Unity.

WebGL is a little more complex, especially considering threads do not exist for WebGL, but its a similar issue there.

Push also throws a kink into this plot, as it's not possible to use assembly stripping with unity if you reference platform specific Unity APIs.

Our road map right now is to fully split out the different parts of our SDK into three major categories:
 - Common (Unity Tasks, Unity Compat, Http Client, storage abstractions, etc.)
 - Core (Most of the public part of 'Parse' right now).
 - Modules (Push, Analytics, Social, etc.)

Once that's done we can properly support all of these other 'fringe' Unity platforms, which I'm super excited to do!

**Comment by balatimuz** [comment]
Something we can expect in soon....?
Thank you

**Comment by montymxb** [comment]
Not likely, this is something we won't be prioritizing although we are aware of it. Closing as we don't intend to fix this as of this time.
