### ISSUE TITLE
[Unity] Support for getting payload info when user taps on device's notification bar (app is in background)

### ISSUE THREAD

**Issue by phonggenix** [parse-community/Parse-SDK-dotNET#161]
Our scenario (Android):

We're making an async multiplayer game, using Parse to manage users, matches,... and also have cloud code to push between users when it's their turn.

The game can receive payload info while it's in foreground. But in the case that it's minimised, when user taps on the notification, the game cannot get payload data.

**Expected:** when user taps on notification, the game opens and can get payload data from the push so that it can load directly into the needed screen.

**Comment by IkeTheDestroyer** [comment]
I had this same problem, I modified the onPushNofticiationRecieved method to always push the payload to unity, not just when it is not paused. https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParsePush/src/main/java/com/parse/ParsePushService.java
line 134.   my change looked like this inside the try block.  
`if(pushPayloadString != null) {
     UnityPlayer.UnitySendMessage("ParseInitializeBehaviour",
    				"OnPushNotificationReceived",
    				pushPayloadString);
     Log.i(TAG, "Push notification is handled while the app is foregrounded.");
    }
    if (!ParsePushUnityHelper.isApplicationPaused()) {
        return;
    }`

It still doesn't pass the data if the application was killed in the background.  Probably won't do a PR because I don't know if this reflects everyones use case.

**Comment by montymxb** [comment]
Closing as out of date.
