### ISSUE TITLE
ParseFacebookUtils issue

### ISSUE THREAD

**Issue by DavePilks** [parse-community/Parse-SDK-dotNET#18]
I am looking through the documentation for the ParseFacebookUtils class and I see that there is a method that can be used to login the user in with their Facebook ID and token. This is great and exactly what I want.

However, when I looked further into the documentation, I saw this

> If a user for the given Facebook credentials does not already exist, a new user will be created.

This is a deal breaker for me. Is there no way to disable this and simply show that the user was not authenticated? I do not want to create a new user if this happens, I just want to show that the login was unsuccessful.

**Comment by animepauly** [comment]
I am not affiliated with Parse, just a developer, BUT I am unsure as to your problem. Are you saying that you think Parse creates a new user on a failed Facebook login? You want them to create a new user if they don't exist so not sure what's exactly the problem. That being said, I have been using Parse for over a year and what you do for logging in with Facebook is this. 

Have a Facebook login button, go through the facebook login setup and it will create a new user if a user with that facebook ID doesn't exist in your app. If they do exist, they login as normal and you get access to their facebook information. 

The tricky part is if the user has created a login already and they want to start using their facebook login instead. What you need to do in that case is to ask the user to login with their Parse Username and ID and then link the Parse User to their Facebook account using LinkAsync() instead of LoginAsync().

**Comment by richardjrossiii** [comment]
@animepauly is correct, that is the flow that we document and support. If you can provide a logical use case for the other work flow, we can definitely discuss it as a team and see if supporting that use-case makes sense for our SDKs.

**Comment by DavePilks** [comment]
Perhaps I didnt express myself, the issue that I was trying to describe was the one highlighted by @animepauly in his final paragraph. 

This line from the documentation 

> If a user for the given Facebook credentials does not already exist, a new user will be created.

suggests that if they do not have a linked FB account but do have a Parse username and password, then a new User entry is created. Is there a way to detect this and prevent it? Basically forcing them to log in with their Parse details.

**Comment by montymxb** [comment]
Closing as this has been mentioned server side in the OS parse-server already.
