### ISSUE TITLE
Why is ParseFacebookUtils-dotNET not open-sourced?

### ISSUE THREAD

**Issue by rihadavid** [parse-community/Parse-SDK-dotNET#185]
I tried to use and modify open-sourced Parse-SDK-dotNET but I am stuck because I can't use ParseFacebookUtils.LogInAsync() because it is not part of the code. What can I do? Could you opensource ParseFacebookUtils-dotNET?

**Comment by richardjrossiii** [comment]
This is due to #169. The eventual plan is to split out ParseFacebookUtils into it's own repository, although that's probably a few months away at this point. 

The unfortunate part about landing #169 is that it meant that some features of the SDK that don't fit into the modules that are ready to go is they're left out. You can still find the source-code of ParseFacebookUtils by looking at the tree when they were last included:

https://github.com/ParsePlatform/Parse-SDK-dotNET/tree/a898c3c54f4e0da6013ca6c36324368f75a67d0c/Parse/Public

(Each platform's implementation of FacebookUtils is inside a folder in there).

If you'd like to contribute to the modularization of the 'Social' part of the SDK, let me know and I can help point you in the right direction to contribute back.

**Comment by AngelKyriako** [comment]
@richardjrossiii is there a repo created for the social related module ? Please let me know about the direction you are talking about above. I am in need of the FacebookUtils as well, therefore if I can help in making it faster, I will.

**Comment by montymxb** [comment]
I believe this has since been open sourced? Correct me if I'm wrong and we'll pop this one back open.
