### ISSUE TITLE
Building throws error

### ISSUE THREAD

**Issue by kitkat14** [parse-community/Parse-SDK-dotNET#231]
Finally after couple of days grinding my teeth i figured out the error was not my code but something with Parse SDK. So the 1.7.0 version is not working at all with android push (using with xamarin).
I read there were some fixes I need but not released to an official release.

Some guide how to build it and make it like a package that you get though nuget ? Because I tried download a clone and use xbuild on it but it throws an error:

/Users/admin/Downloads/Parse-SDK-dotNET-master/Parse.sln (default targets) ->
(Build target) ->
/Users/admin/Downloads/Parse-SDK-dotNET-master/AssemblyLister/AssemblyLister.UWP/AssemblyLister.UWP.csproj (default targets) ->
/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets (GetReferenceAssemblyPaths target) ->

```
/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/xbuild/12.0/bin/Microsoft.Common.targets: error : Unsupported PCL Profile '.NETPortable,Version=v4.6,Profile=Profile32'.
```

**Comment by kitkat14** [comment]
Does anyone even has push working with android + parse server i am on this for days but it doesnt seem to work with all the tutorials that are around

**Comment by unger** [comment]
It is possible to make push working with Android but it requires some work. We made it work by checking out the [1.7.0 tag](https://github.com/ParsePlatform/Parse-SDK-dotNET/releases/tag/1.7.0) and after that fixed a bug with [gcmsenderid ](https://github.com/ParsePlatform/Parse-SDK-dotNET/pull/195/commits/a63ebd3a27e1936aacc1e5cf3ea3f7ecb178f37d). Then there was a problem with Marshmallow (6.0+) that can be fixed by removing [GET_ACCOUNTS permission](https://github.com/ParsePlatform/Parse-SDK-dotNET/pull/223/files).

There are a few more glitches with Android Push for example ParseInstallation is not always saved on device and push messages are often duplicated. We made some quick fixes for these problems too and everything is checked into this [forked branch](https://github.com/heidgert/Parse-SDK-dotNET/tree/tibba). Feel free to check it out and build your own version.

**Comment by montymxb** [comment]
We need to clarify a process for building on your own. Docs are there, but it could be presented in a more transparent fashion.

**Comment by TobiasPott** [comment]
This issue is outdated and no longer applies to the SDK versions available from this repository.
Please feel free to create a new issue if you encounter any problems building the assembly.
Remember to consult the Readme to check for the steps required to build the SDK.
