### ISSUE TITLE
Unity API change in 5.6 beta 6

### ISSUE THREAD

**Issue by ghost** [parse-community/Parse-SDK-dotNET#253]
Unity 5.6 beta 6 introduces the error below (only in Android builds on device, in my testing).  This is due to an API change in Unity 5.6 beta 6 that renames 'Application.bundleIdentifier' to 'Application.identifier':

from https://unity3d.com/unity/beta/unity5.6.0b6

5.6.0b6 Release Notes (Delta since b5)
API Changes
Build Pipeline: Changed 'Application.bundleIdentifier' to 'Application.identifier' and 'PlayerSettings.bundleIdentifier' to 'PlayerSettings.applicationIdentifier'. These now apply to the active target only (Use PlayerSettings.SetApplicationIdentifier to set it for any platform).

-------

adb logcat output from APK build on Android device (Samsung Galaxy S6):

I/Unity   (24349): **MissingMethodException: Method not found: 'UnityEngine.Application.get_bundleIdentifier'.**
I/Unity   (24349):   at Parse.ParseClient.Initialize (Configuration configuration) [0x00000] in <filename unknown>:0
I/Unity   (24349):   at Parse.ParseClient.Initialize (System.String applicationId, System.String dotnetKey, System.String serverURL) [0x00000] in <filename unknown>:0
I/Unity   (24349):   at Parse.ParseInitializeBehaviour.Initialize () [0x00000] in <filename unknown>:0
I/Unity   (24349):   at Parse.ParseInitializeBehaviour.Awake () [0x00000] in <filename unknown>:0
I/Unity   (24349):   at MyParseInitializeBehaviour.Awake () [0x00000] in <filename unknown>:0

**Comment by nah0y** [comment]
I don't know anything about this issue, but looking at the source code for ParseClient.Initialize it never uses bundleIdentifier anywhere :/
https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParseCore/Public/ParseClient.cs

So where is the Parse SDK calling the bundleIdentifier?

**Comment by o3a** [comment]
Thanks for taking the time to look into my issue.  I was getting a bit worried, since there don't seem to be very many responses to issues that other people have posted the past few months.

I couldn't find the call to bundleIdentifier in the current DotNet Parse SDK code either, so I dug deeper using ILSpy to decompile my Parse.Unity.dll and found the call to Application.bundleIdentifier in a file called PlatformHooks.cs.  I'm using a Parse.Unity.dll forked from 1.7.0 that added the serverURL string to ParseClient.Initialize, so I could migrate away from Parse.com in Q4 2016.  I guess that the PlatformHooks.cs file has been removed in more recent updates?  At this point I figured that just using the current Parse.Unity.DLL would resolve the issue that I experienced. 

I tried building a new DLL from the master branch and ran into issues using Visual Studio 2015 (issue #250 already seems to mention this).  Would it be possible for someone to update the released DLL to something newer than 1.7.0?  It's been 13 months since that release and that release won't work anymore anyway since Parse.com has been shut down.

**Comment by nah0y** [comment]
@o3a I also ran into problems compiling the DLL (I'm on a Mac), and a lot of people already asked for a small "last" release, but it seems we can't have that :)

But you can do as I did, which is use a DLL compiled by someone on this thread, right here: https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166#issuecomment-217834669

**Comment by o3a** [comment]
@nah0y Thanks for the DLL, I tried it and it has the same issue as the DLL that I was using before (with Unity 5.6 beta 6). This problem is not blocking me at the moment, since I can get by with Unity 5.6 beta 5 for now, but I don't like the idea of getting stuck on a Unity beta version when they're actively changing and adding features that I need (in this case, Google Daydream and integrated Cardboard VR support).  Since I'm technically not blocked, I can't justify spending the time to get to the bottom of the compilation issues with the current Parse DotNet SDK master branch in Visual Studio 2015.  One option that sounds simpler, would be to install a copy of VS 2013 on a separate Windows machine, since I guess it used to work with that?  

Really, since Parse and the Unity / DotNet SDK is such a critical part of our project, I would like to see it being continuously updated, instead of being stuck using a 13 or 9 month old DLL, as is currently the case.  The combination of that, plus being forced to be on the bleeding edge of Unity's releases, is something that I foresee problems with in the coming weeks.  I'm hoping to preemptively address that, and in the process, help others get updated to a more recent DLL as well.

**Comment by aquaGhost1** [comment]
@o3a we have the same issue with it being core to some projects and your point about unity releases is important.  I think we DO need someone to take over as admin, and make this a real open source effort. 
We started that convo in this thread, I hope it goes somewhere:
https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166#issuecomment-254364431

**Comment by o3a** [comment]
I was able to get past this issue by using ILSpy with the Reflexil plugin to essentially remove the line of code that is incompatible with Unity 5.6 beta 6 and newer.  Reflexil allows you to edit IL code directly and save modified DLL's without having to compile from original source code.

Tools used:
http://ilspy.net
http://reflexil.net

To install Reflexil, just dump all of the Reflexil files into the ILSpy folder.

Tutorial video for using Reflexil to patch a Unity DLL:
https://www.youtube.com/watch?v=fAHvevOFdbo

I am hesitant to post my patched Parse.Unity.dll file at the moment because it hasn't been fully tested yet and I think it may break push notifications.  We are not using push so it works for us so far.  If anyone is using 5.6 beta 6 or newer and experiences this same issue, please message me and I will be happy to send over my patched DLL file.

**Comment by SebastianMaj** [comment]
https://github.com/supersolid/Parse-SDK-dotNET/pull/2

**Comment by vladrad** [comment]
@SebastianMaj I took a look at your PR. It looks great! My only question is where is Platform hooks located? I took a look in my code and I cant find it. Im using latest master version.

**Comment by montymxb** [comment]
@SebastianMaj can you make your PR against this repo? You'd have to catch up to the recent changes however. I'll make a note that this is an outstanding bug in the mean time.

**Comment by ryanspiffy** [comment]
I'm having the same issue; is there anywhere I can download a newer dll that can be used with Unity 2017?  I don't have a windows machine to run through some of the processes mentioned here to patch the current dll.  If anyone is willing to send me a link to a patched dll, I'd greatly appreciate it!

**Comment by montymxb** [comment]
@ryanspiffy there may be a few users who have already built updated DLLs. You might have some look contacting individuals directly that have mentioned building their own DLLs across related issues to this. 

We'll see if we can't target and fix this in preparation for an upcoming release soon here (i.e. before 2018).

**Comment by jcguarinpenaranda** [comment]
How did you get the Unity SDK to work? I'm stuck here :S [#282](https://github.com/parse-community/Parse-SDK-dotNET/issues/282)

**Comment by montymxb** [comment]
Should note that we'll focus on targeting Unity 2017, from there we'll work back as needed.

**Comment by montymxb** [comment]
It's a step on our way to bringing back a revamped sdk :). Just have a lot
to step through haha.

If it is as simple as a renaming a reintegration may be possible by
following the existing implementation, accounting for the name change.

The priority for the moment is to bring up decent tests around the core and
to ensure the core works as expected. Once that's defined and tested to
ensure it stays functional we'll start working on implementations with
other platforms.

**Comment by Cartoman** [comment]
Hi,

Thank you for your prompt response.

As for me, I am currently on a personal development around a game. It takes me a lot of time. My game is today in Alpha version.
I previously looked for how to store and render informations on the Web (for my case, it just concerns connections, scores and reports on scores).
Parse responds perfectly to my problem (and in addition it uses internally MongoDB, which is a NoSQL database that I know) ... except that Parse no longer works under Unity.
**If it can help you, I am candidate to test your developments on Unity in advance of phase**

In the meantime, I'm going to use the **FireBase** environment for my game, while planning to migrate to Parse in the target.

Hoping that you will quickly make the new version.

Cordially

**Comment by montymxb** [comment]
That sounds like a good plan to me! Thanks for letting us know what the
situation is. We'll keep you posted in regards to our progress for
reintegrating unity. That would be fantastic if you want to test drive that
functionality once it's in place.

I haven't looked at firebase in depth but i imagine most of the
functionality is quite similar to what is present in parse. If it's close
enough you might be able to save yourself time by writing a simple
interface for working with firebase. If it's general enough you could then
switch it out for parse (or anything else that's similar for that matter)
and you would only need to adjust how parse interacts with your interface,
rather than all the points dotted throughout your project itself. Just a
thought, but could be nice.

Best of luck with your game by the way!
