### ISSUE TITLE
Need Location for Future NuGet Releases

### ISSUE THREAD

**Issue by montymxb** [parse-community/Parse-SDK-dotNET#278]
Existing nuget releases are available under https://www.nuget.org/packages/parse, which is currently unavailable to the current parse-community team. We'll need to retrieve access in order to continue publishing there or create a **ParseCommunity** specific account for future releases.

@richardjrossiii @hallucinogen is there any chance that either of you have access to the existing account and could assist in passing control to the parse-community team?

**Comment by jaredthirsk** [comment]
Approximately 14 months has gone by since @richardjrossiii and @hallucinogen were tagged with this question.  Is it time to give up and create ParseCommunity?

**Comment by TobiasPott** [comment]
Hi @jaredthirsk 
I wondered if there is any chance to get this issue moving again and I hope that someone from the @parse-community/core-maintainers or @parse-community/guides have any idea on how to progress with this.
More and more issues arise solely because of the outdated version in NuGet but there is nothing worth to call documentation on how to gain access or update it.

Creating a ParseCommunity package might be a way, but I believe it is necessary to clarify upfront that locking the current or any future maintainer out of the system is avoided to the best of our possibilities.

**Comment by TomWFox** [comment]
Interestingly the owner of the package is shown to be @montymxb.

Is there any way of claiming ownership of a package? - if there is no official method I could try getting in contact to claim ownership.

Generally I think it’s always best to have at least a couple people with access in case someone goes off the radar.

**Comment by montymxb** [comment]
@TomWFox Hey, I haven't been an active member for over a year now, but before when I was more engaged I did get the package into my ownership, and away for the old parse one (it was linked to a dead email in fact). It was a hassle to get them to move it over, and I was meaning to hand it over to the community or to flovilmart when he was around, but I got caught up with things :/. 

I would be more than happy to move ownership into the parse-community itself, ideally into the hands of the future maintainers of this repo specifically. It would be great to see this getting some work after so much time 😃 .

Let me know who should be added from the community, and the associated usernames, and I'll get you guys back in there 👍 .

**Comment by TomWFox** [comment]
@montymxb no worries, thanks for responding!

I would be happy for @TobiasPott to be an owner. So that we don’t have a single person with access it would also be good to add some or all of the core team (myself, @dplewis, @acinader, @davimacedo).

@TobiasPott does that sound ok to you?

**Comment by TobiasPott** [comment]
Sorry for the slow response on this, wasn't at a PC for the weekend.

Yes that sounds good to me. =) 
Looking forward to tackle NuGet for the .NET SDK in the future.

Do you need any additional info from myself to get me added or is everything you need accessible here at GitHub?

**Comment by montymxb** [comment]
I can add team members as needed, and once others are on you'll be able to manage it directly. I can only add people who I have NuGet usernames for, so @TobiasPott I'll need yours, and in addition those of any other team members that need to be added.

**Comment by richardjrossiii** [comment]
Hey guys, sorry that nobody from the 'old' parse days helped you out on this.

About a year ago now, the old lastpass that contained logins for all the Parse-related accounts (including AWS, cocoapods, nuget, etc.) has been deleted, due to corporate policy @ FB.

It looks like you guys have found a way around this, which is awesome.

It has been ages since I last touched the NuGet configuration for Parse, and to be honest, even if I had access to the lastpass I'm not 100% sure I could figure out which one linked to this, lol.

If there's any more account-related problems, feel free to reach out to me by notifying me here (unfortunately my current team is not very involved in open-source, so it may take a few months and a bit of nagging for me to notice). I can't promise I can get access to any old accounts at all, but I can track down people who might know.

Thanks for the continued use of Parse. It warms my heart to see the project I put ~2 years of my life making great still be in use.

**Comment by TobiasPott** [comment]
@montymxb I can only provide my username which is TobiasPott (same on NuGet and Github).

@richardjrossiii thank you for your offer and help, I'll check out NuGet as soon as I have access to it and prepare an update for the .NET SDK.

**Comment by TomWFox** [comment]
I’ve made an account on NuGet, my username is TomWFox.

**Comment by montymxb** [comment]
@TobiasPott @TomWFox both of you should have pending invitations to be owners of the project. Let me know that you are both able to get access.

**Comment by TomWFox** [comment]
Got it, thanks a lot. @TobiasPott it will be great to see a new release, ping me if you need anything on the admin / GitHub side of things.

**Comment by TomWFox** [comment]
@montymxb once @TobiasPott has accepted, would you be happy for me to remove you as you’re no longer involved in the project? - of course we would love to add you back if you get involved again in the future 😉

**Comment by montymxb** [comment]
@TomWFox yep I would expect that, it would be most appropriate action given that I'm not actively involved anymore. Once you're both on it it's all yours!

**Comment by TobiasPott** [comment]
@montymxb & @TomWFox I've accepted the invite too and have the Parse package listed under my packages list. Thank you very much for the invite.

**Comment by montymxb** [comment]
Alright, it's all yours guys! Best of luck with everything. Let me know if you need anything else from me in the future.

**Comment by TobiasPott** [comment]
As we have access to NuGet for quite some while and progress has happened on the master branch of this repository I consider this issue closed. 
We will now continue in preparing the next release on NuGet and other useful tasks to get people started with the latest SDK version.

Thank you again for your help @montymxb with this and we are looking forward to see you around and get involved again in the future =).
