### ISSUE TITLE
Unity Exception with Version 2019.1.1f1

### ISSUE THREAD

**Issue by step4** [parse-community/Parse-SDK-dotNET#314]
I am using the fork
[https://github.com/TobiasPott/Parse-SDK-dotNET/tree/feature/recode-unity-support](https://github.com/TobiasPott/Parse-SDK-dotNET/tree/feature/recode-unity-support)

I build it with `dotnet build Parse.sln` and copy the content of `Parse/bin/Debug/netstandard2.0/` into a folder in the Unity project assets.

When I try tu run 
```csharp
ParseClient.Initialize(new ParseClient.Configuration
{
      ApplicationID = "hochschulQuiz",
      Key = "123",
      ServerURI = "http://localhost:8080/api"
});
```
I get the error:
```
NullReferenceException: Object reference not set to an instance of an object
Parse.Internal.AppInformation..cctor () (at C:/projects/Parse-SDK-dotNET/Parse/Internal/Utilities/AppInformation.cs:27)
Rethrow as TypeInitializationException: The type initializer for 'Parse.Internal.AppInformation' threw an exception.
Parse.ParseClient.get_Version () (at C:/projects/Parse-SDK-dotNET/Parse/Public/ParseClient.cs:218)
Parse.ParseClient..cctor () (at C:/projects/Parse-SDK-dotNET/Parse/Public/ParseClient.cs:210)
Rethrow as TypeInitializationException: The type initializer for 'Parse.ParseClient' threw an exception.
Initialization.Start () (at Assets/Scripts/Initialization.cs:12)
```

[On this issue](https://github.com/parse-community/Parse-SDK-dotNET/issues/312#issuecomment-485749629)
TobiasPott mentioned he got it working on 2019.1.0.

Is there something I am missing?

**Comment by TobiasPott** [comment]
Ah yep, unfortunately I've never updated the Readme.md to be more concrete on how to build the unity support branch. I'll bring that one up to date as soon as I can.

The `dotnet build Parse.sln` guide is the one which applies for the master branch.

To get the assemblies for unity support you need to build either the Debug-Unity oder Debug-UnityEditor configuration or both. 
Which configuration you need to build depends on which context you want to use Parse in. If you need it to run from editor scripts there are minor differences which will be build with the Debug-UnityEditor configuration, if you need it solely in runtime (play-mode is considered runtime) Debug-Unity is the configuration you need to build. 
This results in slighly different build commands `dotnet build Parse.sln -c Debug-Unity` and `dotnet build Parse.sln -c Debug-UnityEditor`

This more obvious to notice when opening the solution within Visual Studio and I must admit I did not think about the command line build guide at this point.

**Comment by step4** [comment]
Thanks, compilation worked and the previous error disappeared.

**Comment by TobiasPott** [comment]
You're welcome, I've changed the respective Readme.md to include a hint for that.

**Comment by FcoCGN** [comment]
I tried compile with `dotnet build Parse.sln -c Debug-Unity`, and add the dll file to project. But when i try build project in android platform, have this error:

![image](https://user-images.githubusercontent.com/33829593/58321856-975c3800-7e1f-11e9-99e9-5c6ea85c33c0.png)

Any help?

**Comment by pshannon1000** [comment]
I'm experiencing a similar error using the code in the above-mentioned fork.  
`NullReferenceException: Object reference not set to an instance of an object
Parse.Internal.AppInformation.get_Build () (at /Users/pshannon/Downloads/Parse-SDK-dotNET-feature-recode-unity-support 3/Parse/Internal/Utilities/AppInformation.cs:31)
Parse.ParseClient+Configuration+VersionInformation..cctor () (at /Users/pshannon/Downloads/Parse-SDK-dotNET-feature-recode-unity-support 3/Parse/Public/ParseClient.cs:136)
Rethrow as TypeInitializationException: The type initializer for 'VersionInformation' threw an exception.
Scene.Start () (at Assets/Scene.cs:27)
`

I've tried using a configuration to Initialize, that includes VersionInformation, but it doesn't affect the error.   I'm using Unity 2019.3.0f6.  Would very much appreciate any assistance.

**Comment by TobiasPott** [comment]
@pshannon1000 Could you please make a new issue for your case as it affects a different version of Unity and your stack trace does differ quite a bit.
I'll then take a look at it as soon as I have some spare time.

**Comment by pshannon1000** [comment]
Thanks TobiasPott - I did end up being able to get my Parse / Heroku / Mailgun set-up working in Unity after about 3 days.  I would post my solution here to help others, but at this point I honestly can hardly keep all the parse SDK versions and solutions I tried straight... it does work in the most recent version of Unity however, after hours and hours of trial and error.

**Comment by pshannon1000** [comment]
Ok, ended up having to get into this today again, because the Parse framework was getting an Access Denied error when I trying running my build on iOS...

- All of the errors I've experienced so far can be traced back to the AppInformation.cs file.  

- First, it needs access to UnityEngine.dll to build properly.  Following these instructions can help fix that:
https://www.what-could-possibly-go-wrong.com/unity-and-dlls/
"The first thing we need to do is add a reference to the Unity DLL. To do this you must copy the DLL from your Unity installation to the project that will reference it. To find the DLL go into your local Unity installation (for me that is C:\Program Files\Unity) and navigate to the sub-directory Editor\Data\Managed. Here you will find UnityEngine.dll."

After copying the DLL to the Parse SDK build folder, add a Reference to UnityEngine.dll in the Parse Visual Studio solution.


- The #if Unity compile switches were causing issues for me, so I just simplified and replaced those with the correct values for release builds - string values like "1.0" for version, and Application.persistentDataPath where relevant.  
(Making sure all the paths are supplying "Application.persistentDataPath" is, as always, necessary in Unity)
