### ISSUE TITLE
Is this SDK Compatible With dotnet Core?

### ISSUE THREAD

**Issue by hellfire1980** [parse-community/Parse-SDK-dotNET#320]
Receive the below message when try to compile a self contained application to debian.

warning NU1701: Package 'Parse 1.7.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

**Comment by TheFanatr** [comment]
Parse 1.7.0 is a 3-year-old release of this SDK, and only compatible with a specific few platforms. You can, however, attempt to use it anyways. What is currently recommended is that you compile and reference the master branch, which targets .NET Standard 2.0 and thus is compatible with .NET Core 2.2, or use another distribution that is more suiting to your needs.

**Comment by TobiasPott** [comment]
As the situation of support of .NET Core did not change during the last half year, I close this issue.
Feel free to create a new issue when you encounter any problems with the SDK.

Due to the lack of time the NuGet package has not been updated to the latest state of the repository. This is on our list and scheduled for the next days to update the NuGet package.
