### ISSUE TITLE
How to resend user verification email?

### ISSUE THREAD

**Issue by diasleo98** [parse-community/Parse-SDK-dotNET#336]
Currently i'm only able to send it when i call the SignUpAsync method, i'd like to call it later on when i'm verifying the users accountt.

**Comment by TobiasPott** [comment]
Hi @diasleo98 I'm not sure if I understand you correctly or not.
But first of all, what version of the SDK are you using? 1.7.0 or the 2.0.0 pre-release?

Following your description, it sounds like the expected behaviour to me. Could you elaborate how you mean the part that you want to call it later?
The section in the guide does not explicitly state what happens in case the third 'missing' state is encountered. https://docs.parseplatform.org/dotnet/guide/#verifying-emails 
Did you give it a try and modify your user's mail after creation to trigger the verification process?

I also assume that e-mail creation and distribution is done on the server not on the client SDK. Thus we might check on that on details what triggers e-mails to be sent or possibilities to enforce it (which might not be present in the client SDK yet).

**Comment by diasleo98** [comment]
Thank you @TobiasPott ! If you just update the email to the current it resends the confirmation email!

**Comment by TobiasPott** [comment]
@diasleo98 Glad I could help and you found a way to solve your problem. =)
