### ISSUE TITLE
Ability to compile dotNET SDK within Unity

### ISSUE THREAD

**Issue by keerthik** [parse-community/Parse-SDK-dotNET#354]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-dotNET/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse .NET SDK](https://github.com/parse-community/Parse-SDK-dotNET/releases). 

### Issue Description
Unity support in the 2.0 development branch.
Parse SDK dotNET 2.0.0 development and master branch use .NET language features available in C# 5.0 or newer. Latest Unity still supports only up to .NET 4.0. Realistically, there is no timeline for Unity to upgrade past .NET Framework 4.6.

### Steps to reproduce
- Check out master and import as folder to new Unity project 
- Add .asmdef files within Parse folder
- Launch Unity project in Editor(latest 2018, 2019 or 2020 Unity editor)

### Actual Outcome
A massive list of compile errors in the Unity editor, first failure in most files due to type-testing pattern matching which is a C# 7.0 feature.

### Expected Outcome
With minor tweaks, as suggested in the README.md file to be able to build and compile Parse from within the Unity editor along with the main Unity application.

###  Environment

Server
- Parse Server version: `N/A`
- Operating system: `OSX 11.2.3`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `N/A`

Database
- System (MongoDB or Postgres): `N/A`
- Database version: `N/A`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `N/A`

Client
- Parse .NET SDK version: `2.0.0` [commit f68bde1](https://github.com/parse-community/Parse-SDK-dotNET/commit/f68bde1e89264df183f863c5b601633d2d5dd5ed)

### Logs
Over 1000 errors. Example:
`Infrastructure/RelativeCacheLocationMutator.cs(18,64): error CS1525: Invalid expression term '{'`

**Comment by TobiasPott** [comment]
Hi @keerthik,

I'm unsure what your project setup exactly looks like but according to your description it looks to me like you have imported the sources into your Unity project.

I'm not sure why you would want to use the complete checked out repository into your Unity project as it also includes a Tests-project which is not event intended to be used outside the SDKs visual studio solution. The project is not intended to be build by Unity but the Parse.dll assembly built with Visual Studio or the dotnet CLI can be used within Unity.

Please build the solution instead and use the Parse.dll generated in your Unity project. https://github.com/parse-community/Parse-SDK-dotNET#net-core-cli 
Doing so results in no errors in my case and would allow you to further progress with the given guidance in the readme file.

For the record, this issue is not related to the supported .NET version as it compiles down to a .NET Standard 2.0 assembly which is supported to be used in Unity.

**Comment by keerthik** [comment]
Thanks for reviewing. I was a bit confused earlier, let me clarify -- Parse .NET SDK `master` uses C# 8.0 features, like pattern matching and null coalescing assignment. Unity C# compiler supports different C# versions depending on Unity Editor version.

A workflow with the last official Parse SDK release (v1.8.0) allowed it to be imported into Unity as C# source code, which allowed deeper debugging and modification of the Parse code in the client while being compatible with Unity C#. While I understand this wasn't supported behaviour, it was certainly critical to keeping a working application. For example, v1.8.0 SDK did not provide a public method for clearing the cached ParseUser, and also created an error when logging a user out with an invalid session token — so if for any reason the user's sessiontoken was invalidated remotely, an app reinstall was the only resolution to being able to log in again. Since I had imported SDK source code, I was able to reproduce this error, and expose the `CurrentUserController.ClearFromDisk()` operation to the client application. This would be much more challenging to identify, reproduce, debug and resolve without being able to have Parse SDK code and client code accessible and debuggable in the same build environment.

I understand if this was not and is not intended support, and you can close the issue — just noting that it was a quality of life booster to Unity development that relied on the Parse .NET SDK.

Upon further exploration, I just discovered that Unity 2020.3 and newer supports C# 8.0 and the Parse source code has no compiler errors, which is great news! We cannot use this Editor version yet as it drops support for some mobile devices we still target, but in the near future we may be able to upgrade to the latest Parse SDK and Unity Editor.

**Comment by TobiasPott** [comment]
Hi @keerthik,
I wonder where you got an 'official' version 1.8.0 of the SDK from as I can't find it neither here on github nor in nuget.
Could you please point out to which version you are referring? (the current official release is still 1.7.0 and the 2.0.0 is marked as development state).

The direct support for compilation in Unity is nothing on the agenda at the moment, due to the problem that Unity controls which features are available and which are not and the compilation into a dll/assembly works around this limitation/situation with the Unity platform.

I understand the difficulty which comes with the lack of direct source access within Unity in regards of debugging and error track down. 
Thus said you are welcome to point out the mentioned issues with clearing cached users if they occur with the 2.0.0 develop branch and suggest changes for it. I assume this is an issue others may come across but never got mentioned here on github to be addressed (or got lost over time).

**Comment by keerthik** [comment]
Thanks. I will use the 2.0.0 branch with Unity 2020.3 where it can be compiled from the Editor and see if the issue exists or not, and create a new issue or PR if so (the JS and other language versions of the SDK have this API, so if this SDK is in parity then it is unlikely to be missing).

[This was the branch/tag](https://github.com/parse-community/Parse-SDK-dotNET/tree/legacy-codebase/1.8.0) (I believe), which is labelled 1.8.0 that I was referring to. I see now that it isn't an "official release", but it does have later commits than 1.7.0.

[The version we were using in our codebase](https://github.com/scode-cmd/Parse-for-Unity-2018) looks to be a fork of this (although not forked using git), with some minor modifications for use in Unity.
