### ISSUE TITLE
Parse.ParseUser.LogOutAsync test fails

### ISSUE THREAD

**Issue by mtrezza** [parse-community/Parse-SDK-dotNET#400]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-dotNET/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse .NET SDK](https://github.com/parse-community/Parse-SDK-dotNET/releases). 

### Issue Description

`Parse.ParseUser.LogOutAsync` test fails.

### Steps to reproduce

See https://github.com/parse-community/Parse-SDK-dotNET/actions/runs/12424201056/job/34688986371#step:8:867.

**Comment by mtrezza** [comment]
@YBTopaz8 could you take a look this if you have some time? The CI is currently failing, which may be the issue one can see in your screenshot in https://github.com/parse-community/Parse-SDK-dotNET/pull/393#issuecomment-2547843933. I assume that you fixed this, because the CI passed in that PR, but it turned out that there was a bug in the CI that ignored failing tests. I've this that bug in https://github.com/parse-community/Parse-SDK-dotNET/pull/398, so the CI fails now properly.

**Comment by YBTopaz8** [comment]
Appreciate the insight.
I'm fairly sure it's a test issues as logout works well trying to see from what angle I can fix the test.
Would you like for me to do several PRs as I fix issues moving forward, or would you prefer one PR to be done (before the LQ PR)

By the way for LQ, before release, we will need to do the documentation.
We would need to do the docs for all of .NET since it's still talking about XAMARIN.
If all the same to you, I can update the docs over the weekend - Just need to show me around.

**Comment by mtrezza** [comment]
Yes, please one PR per issue. Keep in mind that 1 PR = 1 changelog entry. The changelog entry describes a single feature change, bug fix, etc.

**Comment by YBTopaz8** [comment]
Good News!
All tests pass even the LogOut and Link.
Bad News : Our coverage probably dropped (since I have now 189 tests instead of 200 as initially)

Another good news: I decided to learn UT so, I'll be adding more UT to improve coverage to be at least back to before v4.0 OR better covered.

Cheers.

**Comment by mtrezza** [comment]
Do you have a PR for this?

**Comment by YBTopaz8** [comment]
#402

**Comment by mtrezza** [comment]
Could you please open a separate PR just for this issue, without including any other changes? I assume it should be a relatively small PR.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.0.1](https://github.com/parse-community/Parse-SDK-dotNET/releases/tag/4.0.1)
