### ISSUE TITLE
Using Parse SDK in Windows 10 Universal App

### ISSUE THREAD

**Issue by techievbv** [parse-community/Parse-SDK-dotNET#63]
Hi, we are working on Windows 10 Universal app and trying to integrate Parse push notifications functionality. We have tried both v1.6.0 and 1.5.5 of Parse SDK to subscribe to a channel using installation.SaveAsync()  or using shorthand like SubscribeAsync() , but, the device is not getting registered (i.e. not subscribing to the channel on Parse portal Installation table). Kindly , let us know if there is a fix available for it.

**Comment by Julien-Mialon** [comment]
Hello, 
I added support for W10, you can check it there : https://github.com/Julien-Mialon/Parse-SDK-dotNET

**Comment by SamAlbuga** [comment]
Same here but it keeps throwing System.Aggregate exception

**Comment by Vaibhavmalik3122** [comment]
@Julien-Mialon we are unable to Build the Parse.UWP project in VS 2015. Errors show HttpClient,Httprequest, etc. not accessible due to its protection level. Please check from your side and Suggest what we can do from our side. Thanks.

**Comment by Julien-Mialon** [comment]
@Vaibhavmalik3122 are you using the Parse nuget ? If yes, you should use the Parse source code directly. There is a small modification on Parse code in order to Parse.UWP use the internal types.

**Comment by Vaibhavmalik3122** [comment]
@Julien-Mialon @richardjrossiii  we are able to build our project using the Parse.UWP reference , and sucessfully registered the username in the Installation table. But, when trying to send a Test push notification via Parse push portal, it is NOT able to sent.

**Comment by richardjrossiii** [comment]
@Vaibhavmalik3122 Yep, that sounds par for the course. Our backend does not currently support UWP push, and won't until we 'officially' support the UWP version of the SDK in an official capacity, sadly.

**Comment by Julien-Mialon** [comment]
@Vaibhavmalik3122 : that sound weird, I'm currently using it with an UWP app without any issues, push notifications work great. It uses the same system than WinRT app.

**Comment by Vaibhavmalik3122** [comment]
@Julien-Mialon could you please elaborate what small modifications on parse code were you talking about for Parse.UWP to use internal types in previous comments ?

**Comment by Julien-Mialon** [comment]
@Vaibhavmalik3122 : you can check my commit for uwp support there : https://github.com/Julien-Mialon/Parse-SDK-dotNET/commit/d6ac21ae89e8b22d30b17daf127c3ac123912b01
Basically, modification in Parse code was in ParseClient.cs to add Parse.UWP to assembly list to use when looking for implementation of interfaces and in AssemblyInfo.Portable.cs add this line [assembly: InternalsVisibleTo("Parse.UWP")] to authorize Parse.UWP project to access internal types of Parse project.

**Comment by mehul9595** [comment]
@Julien-Mialon Could you provide sample solution to use Parse.UWP solution? I tried to use it by creating new UWP project and referencing the library. On app launch adding this line "await ParsePush.SubscribeAsync("");". But it throwing exception Unable to cast object of type 'Parse.ParseObject' to type 'Parse.ParseInstallation'. please help.

**Comment by Vaibhavmalik3122** [comment]
![screenshot 90](https://cloud.githubusercontent.com/assets/8916969/12348246/6e36bbbc-bb8b-11e5-8af3-bb1d796d0e7d.png)
@Julien-Mialon we have the latest pull of the repository and hence all the modifications you talked about are already there(check the screenshot attached).But still we are not able to send push Notifications from parse dashboard. We need to complete this as our official project deadline is coming to an end soon . Would really appreciate if you could assist us on this, maybe a skype call or teamviewer session would help. Looking forward.

**Comment by mehul9595** [comment]
I was able to fix cast exception by referencing Parse.dll and initializing ParseClient.Initialize("key", "key") method. But still no luck with push notifications from Parse console :(

**Comment by Julien-Mialon** [comment]
I just tested this procedure, tell me if it works for you. Otherwise, we can plan teamviewer or skype session to debug that issue.

- create vs project UWP W10
![01-project_creation](https://cloud.githubusercontent.com/assets/2600581/12351857/603e3242-bb81-11e5-9fa0-7dfffa1e9a03.png)
- clone parsesdk github from my profile (with modification for UWP)
- copy Parse & Parse.UWP directory in your project directory
![02-sdkcopy](https://cloud.githubusercontent.com/assets/2600581/12351864/674f749c-bb81-11e5-8a7f-61e6103fe3e8.PNG)
- right click your solution in vs2015 and import project Parse/Parse.csproj and Parse.UWP/Parse.UWP.csproj
- Check that reference to Parse in Parse.UWP is correct
- Add Parse and Parse.UWP in your app reference
![03-parseinstall](https://cloud.githubusercontent.com/assets/2600581/12351867/6cebe6e2-bb81-11e5-9a9f-599a6f5d7e57.PNG)
- Check if everything build correctly

- Go to dev.windows.com
- Create a new app by reserving its name. 
- In my test it will be called "storeTestingStorm"
- Look at your app overview and go to section "Services"/"Push notifications"
![04-storeinfo](https://cloud.githubusercontent.com/assets/2600581/12351870/73b7a132-bb81-11e5-8368-c491cbded3f2.PNG)
- Click on link "Live Services site"
- Copy package SID & client secret to parse configuration page
![05-sid_clientsecret](https://cloud.githubusercontent.com/assets/2600581/12351874/7beeacc4-bb81-11e5-97a4-b98aa0709c96.PNG)


- Go to parse.com and create an app (I called it "testParseUWP")
- Go to push section and scroll down to "Windows Push Credentials". Paste your app SID and client secret
![06-parseconfig](https://cloud.githubusercontent.com/assets/2600581/12351878/80f83e7e-bb81-11e5-8b11-ddcbb78888cc.PNG)
- Go to keys section and copy "Application Id" & ".NET Key" 
![07-parsekeys](https://cloud.githubusercontent.com/assets/2600581/12351884/849de952-bb81-11e5-9074-1595fe360152.png)

- Let's go back in VS 2015
- right click on your app and associate it with your store app (store -> associate app with the store...)
- In your app.xaml.cs constructor, add "ParseClient.Initialize(APPLICATION_ID, .NET_KEY)" where APPLICATION_ID and .NET_KEY are values from parse keys page.
- Add "ParseInstallation.CurrentInstallation.SaveAsync();" just after this line
- Launch your app and suspend it via "Lifecycle events" in VS toolbar (if not available, right click on VS top toolbar and enable "Debug Location") Do not stop the app
![08-lifecycle](https://cloud.githubusercontent.com/assets/2600581/12351889/8e0475ec-bb81-11e5-89f0-68c79e3b71df.PNG)


- Go back to parse.com and send a push notification
- If everything went fine, it shows a push notification on your desktop after a few seconds

**Comment by lukaszkalnik** [comment]
Great guide, thank you @Julien-Mialon! I have made only a small modification: I'm calling `await ParseInstallation.CurrentInstallation.SaveAsync();` in `async onLaunched()` (and not in constructor), as it's an asynchronous method.

**Comment by mehul9595** [comment]
@Julien-Mialon Thanks for steps!
As from the steps you mentioned, I was not doing "ParseInstallation.CurrentInstallation.SaveAsync();" 
but I will try with this change and see if it works. Thanks again!

**Comment by lukaszkalnik** [comment]
Although right now I have the (small) problem that the push opens don't get tracked in Parse.com (only push sends - I see e.g. 2 pushes sent and 0 opened).

My code looks like this:

        public App()
        {
 (...)
            ParseClient.Initialize(app_id, app_key);
        }

(...)

        protected override async void OnLaunched(LaunchActivatedEventArgs e)
        {
(...)
            await ParseInstallation.CurrentInstallation.SaveAsync();

            // By convention, the empty string is considered a "Broadcast" channel
            // Note that we had to add "async" to the OnLaunched definition to use the await keyword
            await ParsePush.SubscribeAsync("");

            // Track this application being launched
            await ParseAnalytics.TrackAppOpenedAsync(e);
        }

Any suggestions?

Thanks so much!

**Comment by mehul9595** [comment]
I tried with above steps but still cannot send push successfully, this is what i see on Parse dashboard
![image](https://cloud.githubusercontent.com/assets/6695245/12381719/ae40f664-bdca-11e5-8cdc-0436651f9e32.png)

**Comment by Julien-Mialon** [comment]
@lukaszkalnik @mehul9595 about the opened notification count, it's an issue from Parse. I just tried with the WinRT sdk (nuget 1.7.0), it doesn't work either. The sdk expect to receive a json with "push_hash" field to track push notification open count. And this field is not sent by Parse backend, just receiving something like {"alert":"push notification message"}

**Comment by lukaszkalnik** [comment]
@Julien-Mialon cool, thanks so much for the information! You are really helping a lot, I appreciate it!

**Comment by Julien-Mialon** [comment]
@lukaszkalnik I just opened a dedicated issue (#162) for the problem with the missing field in json notification.

**Comment by Vaibhavmalik3122** [comment]
@Julien-Mialon Notifications are working good. Thanks for the steps. But, one issue is bugging us , whenever the app is in Foreground state , the toast notification banner does not appear , even after the app is closed , no notification appears in Action center. The ParsePush.PushNotificationReceived is hit everytime , but on the OS level no notification shows up.

**Comment by Julien-Mialon** [comment]
@Vaibhavmalik3122 I just tested foreground notifications and it works without issue, can you check with the project available there : https://github.com/Julien-Mialon/Parse.UWP.Sample, you just have to associate the app with the store and write your Parse appid and .net key in Constants.cs.

If it's doesn't work for you, check if in the event handler of PushNotificationReceived, args.NotificationType == "Toast" and args.Cancel is not set to true.

**Comment by michstmatt** [comment]
I followed your steps, the app has been associated with the store, and I had it working in December, now it is randomly not working (I had not tested it for some time because I had got it working). Do you have any more suggestions?

**Comment by Julien-Mialon** [comment]
@michstmatt If it's randomly working, I can not really think of something from the app that can block this. But I saw some issue from Windows notification service working sometimes.

**Comment by mehul9595** [comment]
@Julien-Mialon I was wondering if its possible to send 'adaptive toast notificatoins' which are supported by win10 adaptive templates (ref: http://blogs.msdn.com/b/tiles_and_toasts/archive/2015/07/08/toast-notification-and-action-center-overview-for-windows-10.aspx) 
As I can see from Parse dashboard it only allows to send Plain Text or Json data into Push notification. Is there additional things needs to be done in order to these custom push notifications?

**Comment by Julien-Mialon** [comment]
@mehul9595 Not supported for now but I think there is another opened issue about that. https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/137

**Comment by mehul9595** [comment]
@Julien-Mialon well exactly what I was looking for. thanks again!

**Comment by michstmatt** [comment]
@Julien-Mialon I created a new project, I found out that when I copy the Package SID its adds a blank character at the end. Went back into my original projects parse push settings, sure enough blank character at the end, and its working. Thanks for making this library!

**Comment by mehul9595** [comment]
@Julien-Mialon is it possible to send push notification with deeplink? if yes, how can it be handled?

**Comment by Julien-Mialon** [comment]
@mehul9595 I think you can do that by sending json content in your notification and then parsing this content in your application. You can embed deeplink info in this json.

**Comment by Julien-Mialon** [comment]
@lukaszkalnik @mehul9595  I just implemented support to track opened notification count in WinRT & winPhone (https://github.com/ParsePlatform/Parse-SDK-dotNET/pull/164) and did the same modification on my uwp fork you can find here : https://github.com/Julien-Mialon/Parse-SDK-dotNET/tree/features/uwpSupport

**Comment by lukaszkalnik** [comment]
Thanks @Julien-Mialon, I have just tested the opened pushes reporting and it works flawlessly. Great job!

The only weird thing is that now I get an error when starting the Release build on a Windows 10 Mobile device:
0x76CCE031 (combase.dll) in ApplicationName.exe: 0xC000027B: An application-internal exception has occurred (Parameter: 0x038E60F8, 0x00000002).
When I start a Debug build though everything is working correctly.

On a Windows 10 PC both Debug and Release builds are working correctly.

**Comment by lukaszkalnik** [comment]
Hmm, I just checked and with your previous version of the SDK I have actually the same problem (Release build not working on a smartphone). Probably this is unrelated to your changes then.

Thanks for your awesome help!

**Comment by SamAlbuga** [comment]
@Julien-Mialon Thank you, great job! I have a problem with receiving push notifications. After implementing ParsePush.ParsePushNotificationReceived, Parse.UWP throws System.NullReferenceException when the app receives a notification

**Comment by Julien-Mialon** [comment]
@SamAlbuga I think you have to subscribe to 2 event, ParsePushNotificationReceived and PushNotificationReceived.

**Comment by mehul9595** [comment]
@Julien-Mialon is it under master yet? which branch do you suggest to use?

**Comment by Julien-Mialon** [comment]
For uwp, you can use the branch "features/uwpSupport" on my repo. Not merged with official parse repo for now. https://github.com/Julien-Mialon/Parse-SDK-dotNET

**Comment by mehul9595** [comment]
cool, I was using master branch from your repo so far working fine for me without issues. I will change to your feature branch.

**Comment by SamAlbuga** [comment]
@Julien-Mialon Yes that worked perfectly. Thank you :)

**Comment by Vaibhavmalik3122** [comment]
Hey @Julien-Mialon , when app is in foreground, how can we create a custom toast notif. for the user such that, when clicked, a custom event can be hit instead of Onlaunched. for reference , WhatsApp for WP is a good example.

**Comment by mehul9595** [comment]
@Vaibhavmalik3122 I don't think if that's possible, seems it is an part of enhancement, [137](https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/137) . Once interactive notifications is supported this can be achieved.

**Comment by mehul9595** [comment]
I found a case where push notification is sent during device is power off, notifications are not delivered on tablet device when tablet is powered on. 
On Windows phone, push notification is seen when device is powered on. 
Any clue?

**Comment by lukaszkalnik** [comment]
@Julien-Mialon we are currently testing and turns out I cannot start the app with Parse SDK in Release mode on a Lumia 930 phone. It starts in Debug mode though... I get the following exception:
Exception at 0x777AE031 (combase.dll) in App.exe: 0xC000027B: An application-internal exception has occurred (Parameter: 0x00894FC8, 0x00000002)

**Comment by TobiasPott** [comment]
Based on the latest version in the master branch using the Parse SDK on UWP platforms does work.
If any specific problem re-occurs with the latest version from the master branch, feel free to create a new issue to discuss possible solutions.
